server:
  port: 8090

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/blueisland?serverTimezone=Asia/Seoul // 로컬 호스트
#    url: jdbc:mysql://172.25.43.123:3306/blueisland?serverTimezone=Asia/Seoul // 도커 빌드용
    url: jdbc:mysql://192.168.0.152:3306/blueisland?serverTimezone=Asia/Seoul
    username: uni
    password: uni1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/productimgs/
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  # WebConfig에 세팅
  #add-resource-locations: classpath:/static/productimgs/
  #add-resource-handler: /productimgs/**

  add-resource-locations: /productimgs/
  add-resource-handler: /productimgs/**


  # ProductService에 세팅
  #image-dir: src/main/resources/static/productimgs/
  image-dir: /productimgs/
  #image-url: http://43.200.33.166:8090/productimgs/
  #image-url: http://192.168.0.24:8090/productimgs/
  image-url: http://localhost:8090/productimgs/

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용
jwt:
  secret: dW5pLXJlYWN0LW5naW54LXNwcmluZy1ib290LWp3dC1vcmFjbGUtZG9ja2VyLWVjMi1yZWFjdC1uZ25peC1zcHJpbmctYm9vdC1qd3Qtb3JhY2xlLWRvY2tlci1lYzIK

#  echo 'uni-react-nginx-spring-boot-jwt-oracle-docker-ec2-react-ngnix-spring-boot-jwt-oracle-docker-ec2'|base64

mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.uni.blueisland
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info


